[2025-05-29T21:31:16.212Z] info: kubernetes.yaml was copied to the config folder
[2025-05-29T21:37:02.135Z] info: bookmarks.yaml was copied to the config folder
[2025-05-29T21:37:02.186Z] info: widgets.yaml was copied to the config folder
[2025-05-29T21:37:02.199Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:37:02.187Z] info: custom.css was copied to the config folder
[2025-05-29T21:37:02.188Z] info: custom.js was copied to the config folder
[2025-05-29T21:37:02.300Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.305Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.312Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.319Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.326Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.332Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.340Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.348Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.357Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:02.691Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:37:02.702Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:37:02.709Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:37:02.714Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:37:02.832Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:37:02.962Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:37:03.246Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.263Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.269Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.274Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.283Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.289Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.334Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:37:03.335Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:37:03.335Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:37:03.377Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.381Z] error: <httpProxy> Error calling https://portainer:9000/api/endpoints/3/docker/containers/json...
[2025-05-29T21:37:03.382Z] error: <httpProxy> [
  500,
  [Error: write EPROTO 58F2351196750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2025-05-29T21:37:03.383Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer:9000/api/endpoints/3/docker/containers/json?all=1
[2025-05-29T21:37:03.402Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.407Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:37:03.421Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:03.499Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:37:03.542Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:37:03.614Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.
[2025-05-29T21:37:11.158Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.173Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.228Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.244Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.268Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.275Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.278Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:37:11.278Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:37:11.279Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:37:11.280Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:37:11.290Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.292Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:37:11.301Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.342Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:37:11.360Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:37:11.397Z] error: <httpProxy> Error calling https://portainer:9000/api/endpoints/3/docker/containers/json...
[2025-05-29T21:37:11.398Z] error: <httpProxy> [
  500,
  [Error: write EPROTO 58F2351196750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2025-05-29T21:37:11.398Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer:9000/api/endpoints/3/docker/containers/json?all=1
[2025-05-29T21:37:11.512Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.
[2025-05-29T21:37:14.027Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.
[2025-05-29T21:37:22.025Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.
[2025-05-29T21:38:10.805Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.824Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.843Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.858Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.876Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.881Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.925Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:38:10.961Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:10.967Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:11.008Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:38:11.010Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:11.050Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.
[2025-05-29T21:38:11.082Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:38:11.083Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:38:11.083Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:38:11.085Z] error: <httpProxy> Error calling https://portainer:9000/api/endpoints/3/docker/containers/json...
[2025-05-29T21:38:11.086Z] error: <httpProxy> [
  500,
  [Error: write EPROTO 58F2351196750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2025-05-29T21:38:11.086Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer:9000/api/endpoints/3/docker/containers/json?all=1
[2025-05-29T21:38:11.088Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:38:12.150Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.155Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.168Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.184Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.214Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.221Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.223Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:38:12.228Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.267Z] error: <httpProxy> Error calling https://portainer:9000/api/endpoints/3/docker/containers/json...
[2025-05-29T21:38:12.268Z] error: <httpProxy> [
  500,
  [Error: write EPROTO 58F2351196750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2025-05-29T21:38:12.268Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer:9000/api/endpoints/3/docker/containers/json?all=1
[2025-05-29T21:38:12.274Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.281Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:12.289Z] error: <qbittorrentProxyHandler> HTTP 403 logging in to qBittorrent.  Data: Your IP address has been banned after too many failed authentication attempts.
[2025-05-29T21:38:12.297Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:38:12.298Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:38:12.299Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:38:12.319Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:38:12.330Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:38:17.677Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.693Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.704Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: connect EACCES /var/run/docker.sock] {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-05-29T21:38:17.714Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.743Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.747Z] error: <httpProxy> Error calling https://portainer:9000/api/endpoints/3/docker/containers/json...
[2025-05-29T21:38:17.747Z] error: <httpProxy> [
  500,
  [Error: write EPROTO 58F2351196750000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2025-05-29T21:38:17.747Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer:9000/api/endpoints/3/docker/containers/json?all=1
[2025-05-29T21:38:17.756Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.774Z] error: <credentialedProxyHandler> HTTP Error 403 calling http://overseerr:5055/api/v1/request/count
[2025-05-29T21:38:17.804Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.807Z] error: <plexProxyHandler> HTTP 401 communicating with Plex. Data: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
[2025-05-29T21:38:17.815Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.826Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.843Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-29T21:38:17.845Z] error: <qbittorrentProxyHandler> HTTP 403 logging in to qBittorrent.  Data: Your IP address has been banned after too many failed authentication attempts.
[2025-05-29T21:38:17.861Z] error: <httpProxy> Error calling http://paperless:8156/api/statistics/...
[2025-05-29T21:38:17.862Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.9:8156
      at <unknown> (Error: connect ECONNREFUSED 172.18.0.9:8156) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.9',
    port: 8156
  }
]
[2025-05-29T21:38:17.862Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless:8156/api/statistics/?format=json
[2025-05-29T21:38:22.917Z] error: <qbittorrentProxyHandler> HTTP 403 logging in to qBittorrent.  Data: Your IP address has been banned after too many failed authentication attempts.
[2025-05-29T21:38:27.930Z] error: <qbittorrentProxyHandler> HTTP 403 logging in to qBittorrent.  Data: Your IP address has been banned after too many failed authentication attempts.
